# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22cb6298ddf6eb04cba7b11edd678da2b2dc78cd48d1d049e353f111ae3a7e35d2b1cf366676527b03813d3d17ec6bb6769df29d9d9003c67adb9e0431e0c894

test:
  secret_key_base: 622efcbf698e19e0cde5bdfcab80e58a26ba04799bb6b9507a29dd4cd5e68ff95bf47ded092bb995cde3376b7f6fd467d201d9ea236aae00a11459b2c3ba45d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
